#!/bin/bash

rm -v /etc/gitlab/.not_configured

DEBIAN_FRONTEND="noninteractive" EXTERNAL_URL="http://gitlab.at.home" apt install -y gitlab-ce

systemctl disable gitlab-first-run.service

curl -L -o /etc/gitlab/gitlab.rb http://gateway/gitlab/gitlab.rb

gitlab-ctl reconfigure

reboot

