#!/bin/bash

rm -v /etc/gitlab/.not_configured

DEBIAN_FRONTEND="noninteractive" EXTERNAL_URL="http://gitlab.at.home" apt install -y gitlab-ce

systemctl disable gitlab-first-run.service

curl -L -o /etc/gitlab/gitlab.rb http://gateway/gitlab/gitlab.rb

gitlab-ctl reconfigure

GITLAB_URL="https://gitlab.at.home"
SETUP_RB="/usr/local/sbin/initial-setup.rb"
TOKEN=$(gitlab-rails runner ${SETUP_RB})

gitlab-runner register \
    --non-interactive \
    --name "gitlab.at.home-default" \
    --url "${GITLAB_URL}" \
    --registration-token "${TOKEN}" \
    --executor "shell" \
    --locked=false

reboot
