version: "3"

networks:
    gitea:
        external: false

services:
    server:
        image: gitea/gitea:1.13.2
        container_name: gitea
        environment:
            - APP_NAME="gitea.at.home"
            - RUN_MODE=prod
            - DOMAIN=gitea.at.home
            - SSH_DOMAIN=gitea.at.home
            - LFS_START_SERVER=true
            - INSTALL_LOCK=false
            - SECRET_KEY=1234567890qazwsxedcrfvtgbyhnujmikolp
            - DISABLE_REGISTRATION=true
            - REQUIRE_SIGNIN_VIEW=true
            - USER_UID=1000
            - USER_GID=1000
            - DB_TYPE=postgres
            - DB_HOST=db:5432
            - DB_NAME=gitea
            - DB_USER=gitea
            - DB_PASSWD=gitea
        restart: always
        networks:
            - gitea
        volumes:
            - /var/local/docker/gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "3000:3000"
            - "222:22"
        depends_on:
             - db

    db:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=gitea
            - POSTGRES_PASSWORD=gitea
            - POSTGRES_DB=gitea
        networks:
            - gitea
        volumes:
            - /var/local/docker/postgres:/var/lib/postgresql/data